#.travis.yml

language: node_js
node_js:
  - "node"

branches:
  only:
    - master

script:
  - npm run build
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run deploy; fi

notifications:
  email:
    on_failure: change