#.travis.yml

language: node_js
node_js:
  - "node"

branches:
  only:
    - master

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then yarn build; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn deploy; fi

notifications:
  email:
    on_failure: change