#.travis.yml

language: node_js
node_js:
  - "11.3"
python:
  - "2.7"

branches:
  only:
    - master

# https://github.com/travis-ci/travis-ci/issues/7471#issuecomment-367005802
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then yarn build; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn deploy; fi

notifications:
  email:
    on_failure: change