#.travis.yml

language: node_js
node_js:
  - "node"
python:
  - "2.7"

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then yarn build; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then yarn deploy; fi

notifications:
  email:
    on_failure: change